### ISSUE TITLE
Message: Connection reset Caused by: java.lang.RuntimeException: java.lang.RuntimeException: ParseError at [row,col]:[18785,80]

### ISSUE THREAD

**Issue by jaeyoungpark** [splunk/splunk-sdk-java#105]
I'm running a script that executes multiple queries and whenever the script runs for some time, It hits this: 

`Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: ParseError at [row,col]:[18785,80]
Message: Connection reset
	at com.splunk.ResourceCollection.refresh(ResourceCollection.java:332)
	at com.splunk.ResourceCollection.refresh(ResourceCollection.java:29)
	at com.splunk.Resource.validate(Resource.java:174)
	at com.splunk.ResourceCollection.validate(ResourceCollection.java:350)
	at com.splunk.ResourceCollection.get(ResourceCollection.java:184)
	at com.splunk.SavedSearch.dispatch(SavedSearch.java:87)
	at com.splunk.SavedSearch.dispatch(SavedSearch.java:106)
	at com.splunk.SavedSearch.dispatch(SavedSearch.java:63)
	at cspAnomalyBaseline.SplunkDBCPU.runDBCPU(SplunkDBCPU.java:70)
	at cspAnomalyBaseline.mainRun.main(mainRun.java:98)
	at cspAnomalyBaseline.Automation.main(Automation.java:81)
	... 5 more
Caused by: java.lang.RuntimeException: ParseError at [row,col]:[18785,80]
Message: Connection reset
	at com.splunk.AtomObject.scan(AtomObject.java:198)
	at com.splunk.AtomEntry.parseValue(AtomEntry.java:245)
	at com.splunk.AtomEntry.parseDict(AtomEntry.java:143)
	at com.splunk.AtomEntry.parseStructure(AtomEntry.java:189)
	at com.splunk.AtomEntry.parseValue(AtomEntry.java:230)
	at com.splunk.AtomEntry.parseDict(AtomEntry.java:143)
	at com.splunk.AtomEntry.parseContent(AtomEntry.java:118)
	at com.splunk.AtomEntry.init(AtomEntry.java:95)
	at com.splunk.AtomObject.load(AtomObject.java:121)
	at com.splunk.AtomEntry.parse(AtomEntry.java:77)
	at com.splunk.AtomFeed.init(AtomFeed.java:95)
	at com.splunk.AtomObject.load(AtomObject.java:121)
	at com.splunk.AtomFeed.parse(AtomFeed.java:80)
	at com.splunk.AtomFeed.parseStream(AtomFeed.java:59)
	at com.splunk.ResourceCollection.refresh(ResourceCollection.java:330)
	... 15 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[18785,80]
Message: Connection reset
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:591)
	at com.splunk.AtomObject.scan(AtomObject.java:193)
	... 29 more`

Since this error occurs in random queries every time, I'm guessing this connection reset is not because of my code itself. 
I've also read the previous issue that has been closed: it does give some explanation why this might happen but doesn't say anything about fixing it.
Does spunk connections automatically timeout after a given amount of time? More importantly, is there a way to prevent this from happening? 

FYI, using JDK 1.8 and splunk 1.5

**Comment by shakeelmohamed** [comment]
Related to internal ticket DVPL-7228
