### ISSUE TITLE
latest SDK failed with JDK 1.6 and JDK 1.7 , Connection reset error

### ISSUE THREAD

**Issue by kenshinxu1** [splunk/splunk-sdk-java#145]
Follow the SDK guide and try to run sdk samples in ssl_protocol folder, 
In SDK spec it mentioned we need a JDK 6 or later , but I tried with JDK 1.6/1.7/1.8 and find it only work with JDK 1.8 with proper settings.

**with JDK 1.8 , the connection could be successful with TLS v1.2,custom SSL and custom CLS**
Below is the log
```
class:  com.splunk.examples.ssl_protocols.Program
Your Java version is: 8
Now trying to connect to Splunk using SSLv3
	 Failure! 
Now trying to connect to Splunk using TLSv1
	 Failure! 
Now trying to connect to Splunk using TLSv1.1
	 Failure! 
Now trying to connect to Splunk using TLSv1.2
	 Success!
Now trying to connect to Splunk using a custom SSL only SSLSocketFactory
	 Success!
Now trying to connect to Splunk using a custom TLS only SSLSocketFactory
	 Success!

Process finished with exit code 0

```

**with JDK 1.6 & JDK 1.7, I could not get any successful connection**
below is the log:
Your Java version is: 6
Now trying to connect to Splunk using SSLv3
	 Failure! 
Now trying to connect to Splunk using TLSv1
	 Failure! 
Now trying to connect to Splunk using TLSv1.1
	 Failure! 
Now trying to connect to Splunk using TLSv1.2
	 Failure! 
Now trying to connect to Splunk using a custom SSL only SSLSocketFactory
	 Failure!
Now trying to connect to Splunk using a custom TLS only SSLSocketFactory
	 Failure!

Errors:
Basically got connection reset error

java.lang.RuntimeException: Remote host closed connection during handshake
	at com.splunk.HttpService.send(HttpService.java from InputFileObject:451)
	at com.splunk.Service.send(Service.java from InputFileObject:1295)
	at com.splunk.HttpService.post(HttpService.java from InputFileObject:348)
	at com.splunk.Service.login(Service.java from InputFileObject:1124)
	at com.splunk.Service.login(Service.java from InputFileObject:1103)
	at com.splunk.Service.connect(Service.java from InputFileObject:189)
	at com.splunk.examples.ssl_protocols.Program.main(Program.java from InputFileObject:58)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:882)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1188)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1215)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1199)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:434)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1031)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:230)
	at com.splunk.HttpService.send(HttpService.java from InputFileObject:445)
	... 6 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:462)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:863)
	... 14 more

some other error with JDK 1.7 
Your Java version is: 7
Now trying to connect to Splunk using SSLv3
java.lang.RuntimeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at com.splunk.HttpService.send(HttpService.java:451)
	at com.splunk.Service.send(Service.java:1295)
	at com.splunk.HttpService.post(HttpService.java:348)
	at com.splunk.Service.login(Service.java:1124)
	at com.splunk.Service.login(Service.java:1103)
	at com.splunk.Service.connect(Service.java:189)
	at com.splunk.examples.ssl_protocols.Program.main(Program.java:58)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.Handshaker.activate(Handshaker.java:470)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1438)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1308)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1092)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.splunk.HttpService.send(HttpService.java:445)
	... 6 more

**Comment by ncanumalla-splunk** [comment]
Closing this issue with recommended versions in above comment.
