### ISSUE TITLE
Splunk Java SDk not supporting sslCertPath while writing to outputs.conf

### ISSUE THREAD

**Issue by vpnjain1991** [splunk/splunk-sdk-java#174]
As per splunk doc (https://docs.splunk.com/Documentation/Splunk/8.2.2/Admin/Outputsconf) we need to write _clientCert_ : <client certificate> in $SPLUNK_HOME/etc/system/local/outputs.conf for TLS communication on splunk universal forwarder.
After upgrading splunk forwarder to 8.xx while its trying to save configuration for TLS communication. Its faling wiht below exception- 

2021-10-25 16:27:51,387 ERROR [SplunkForwarderConfigController.addSplunkIndexer:114] (http-nio-127.0.0.1-9081-exec-3:[])  Error occurred when adding splunk indexer10.8.2.146:9700 to forwarder
com.splunk.HttpException: HTTP 400 -- Argument "sslCertPath" is not supported by this handler.
	at com.splunk.HttpException.create(HttpException.java:84) ~[splunk-1.6.5.0.jar:1.6.5]
	at com.splunk.HttpService.send(HttpService.java:500) ~[splunk-1.6.5.0.jar:1.6.5]
	at com.splunk.Service.send(Service.java:1295) ~[splunk-1.6.5.0.jar:1.6.5]
	at com.splunk.HttpService.post(HttpService.java:348) ~[splunk-1.6.5.0.jar:1.6.5]
	at com.splunk.Entity.update(Entity.java:438) ~[splunk-1.6.5.0.jar:1.6.5]
	at com.splunk.Entity.update(Entity.java:450) ~[splunk-1.6.5.0.jar:1.6.5]

**Comment by vpnjain1991** [comment]
@bparmar-splunk  have you tried ?

**Comment by bparmar-splunk** [comment]
@vpnjain1991,
Yes, we have tried with splunk version 1.7.1. Please check the attachments for reference.
Test code works fine and attachments also contains result.

<img width="1792" alt="Screenshot 2021-11-03 at 16 59 50" src="https://user-images.githubusercontent.com/84167435/140687687-e7953f4e-bee5-477f-bcc5-3e50ceef34ce.png">
<img width="1792" alt="Screenshot 2021-11-03 at 17 01 09" src="https://user-images.githubusercontent.com/84167435/140687708-25583470-557a-494f-8752-d3bec4e3f1cc.png">

**Comment by bparmar-splunk** [comment]
@vpnjain1991,
It seems your issue has been resolved as per above mentioned comment.

Hence, closing this ticket.

**Comment by vpnjain1991** [comment]
@bparmar-splunk  yes issue can be closed but it would have been better if clientCert getter, setter are added to OutputServer class.

**Comment by bparmar-splunk** [comment]
@vpnjain1991,
Sure. We will take care of that thing.
Thank you !
