### ISSUE TITLE
splunk sdk : com.splunk.HttpException: HTTP 401 -- call not properly authenticated

### ISSUE THREAD

**Issue by radhika123456789** [splunk/splunk-sdk-java#62]
I am trying to search the string from splunk , i was getting 401 error.
StringBuilder searchString = new StringBuilder();

```
    searchString.append("search").append(" XXX");
```

Service service = Service.connect(splunkArgs);
Job job = service.getJobs().create(searchString.toString());

**Comment by ivansd** [comment]
This issue is still present:

ServiceArgs loginArgs = new ServiceArgs();
loginArgs.setUsername("username");
loginArgs.setPassword("password"); 
loginArgs.setHost(host);
loginArgs.setPort(Integer.parseInt(port));
Service.connect(loginArgs); 

Then, I check if login is successful by having this line of code:

System.out.println("Installed apps: " + service.getApplications().keySet());
I get all apps and then search with JobExportArgs exportArgs = new JobExportArgs();

exportArgs.setEarliestTime("-5");
exportArgs.setLatestTime("now");
exportArgs.setRequiredFieldList("string");
exportArgs.setSearchMode(JobExportArgs.SearchMode.NORMAL);
InputStream exportSearch = service.export(searchQuery, exportArgs);

Call fails with - com.splunk.HttpException: HTTP 401 -- call not properly authenticated

**Comment by shakeelmohamed** [comment]
@ivansd can you provide us with some details about your environment? (Splunk version, OS, load balancer, etc.)

**Comment by ppchava** [comment]
we are also experiencing similar issue 'com.splunk.HttpException: HTTP 401 -- call not properly authenticated' while trying to connect to Splunk.. we are

Here is code snippet.
                ServiceArgs loginArgs = new ServiceArgs();
		loginArgs.setUsername(username);
		loginArgs.setPassword(password);
		loginArgs.setHost(host);
		loginArgs.setPort(port);
		loginArgs.setApp(app);
		Service splunkSrv = Service.connect(loginArgs);

**Comment by itay** [comment]
Since we know this code path works, the best suggestion for this issue is to open a support ticket via support@splunk.com with your Support entitlements, since it may be something specific to your environment.

**Comment by shakeelmohamed** [comment]
Closing due to inactivity

**Comment by nmaiorana** [comment]
HTTP 401 -- {"messages":[{"type":"WARN","text":"call not properly authenticated"}]}

We are seeing this error intermittently. From what I can tell, it happens after the request is submitted to the server. I even suspect the query itself is being executed. I suspect this because our Splunk team is reporting more concurrent sessions for our user than is possible for us.

Is it possible the error messes is incorrect? I ask this because we get this once in a while from a process that is running and submits the request in the same way every time.

**Comment by tdhellmann** [comment]
Hi @nmaiorana - It would help us to know a bit more about your situation: 

Which version of Splunk Enterprise, the Splunk Java SDK, and Java are you running on?
What does your Splunk Enterprise deployment look like (SHC, load balancing, etc.) ? 
Can you provide a code snippet that leads to the error? 
How many concurrent sessions are you seeing for your user?
How long does your search take to process?

Thanks

**Comment by mdharmesh** [comment]
@nmaiorana Even I am facing the same issue. Mainly it occurs once in a while.

**Comment by RakeshAMore** [comment]
facing same issue. I have verified that my username and password is correct but this is mainly happening when I tried to make multiple calls at time using multiple threads.

**Comment by RakeshAMore** [comment]
I am able to resolve this issue by minimising number of concurrent requests to splunk server, now it is working fine  thanks

**Comment by pawarakesh** [comment]
I was getting the same error. I have fixed this problem by upgrading splunk-sdk-java library from 1.3.2 to 1.6.5 (latest one). Now it's working fine.

**Comment by SurajMenon** [comment]
I am seeing the issue even after upgrading to 1.6.5. 
Following is the maven dependency that I have:

<dependency>
	<groupId>com.splunk</groupId>
	<artifactId>splunk</artifactId>
	<version>1.6.5.0</version>
</dependency>

**Comment by pawarakesh** [comment]
try to download , use it and see if it fixes, http://dev.splunk.com/goto/sdk-java-jar , you can add this manually in your maven repo/build server/common repo .

**Comment by SurajMenon** [comment]
Even with the jar from Splunk I get the issue.

**Comment by shakeelmohamed** [comment]
@SurajMenon I've reopened this issue so we don't lose it. If you have some repro steps, we can take a look when we get around to it. We're always open to a PR if you're interested in contributing!

**Comment by aggie05engineer** [comment]
This may be related to session expiration and the lack of threading controls in the SDK. See my other recent ticket https://github.com/splunk/splunk-sdk-java/issues/139.

**Comment by Abrar-Snap** [comment]
Is this fixed somewhere or still an issue? I still see this error. 


Caused by: com.splunk.HttpException: HTTP 401 -- call not properly authenticated
	at com.splunk.HttpException.create(HttpException.java:84)
	at com.splunk.HttpService.send(HttpService.java:452)
	at com.splunk.Service.send(Service.java:1293)
	at com.splunk.HttpService.get(HttpService.java:150)
	at com.splunk.Entity.refresh(Entity.java:381)
	at com.splunk.Entity.refresh(Entity.java:24)
	at com.splunk.Resource.validate(Resource.java:174)
	at com.splunk.Entity.validate(Entity.java:462)
	at com.splunk.Entity.getContent(Entity.java:157)
	at com.splunk.Entity.getString(Entity.java:279)
	at com.splunk.ServiceInfo.getVersion(ServiceInfo.java:155)
	at com.splunk.Service.login(Service.java:1128)

**Comment by bparmar-splunk** [comment]
Hi @Abrar-Snap,
We are recommending users to make use of **Bearer** token instead of Splunk token, because it is configurable and long lived token.
