### ISSUE TITLE
job.getEventCount() throws null pointer exception when too many events

### ISSUE THREAD

**Issue by francispage** [splunk/splunk-sdk-java#81]
We have a couple of events in our Splunk deployment and we can't get the eventCount (actually no result at all because the exception is catched at higher level) when the number of event is too big.

This is only for a week of data so it's very problematic in our case.

Splunk.java.lang.NumberFormatException: For input string: "2335707040"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:495)
        at java.lang.Integer.parseInt(Integer.java:527)
        at com.splunk.Value.toInteger(Value.java:136)
        at com.splunk.Record.getInteger(Record.java:121)
        at com.splunk.Entity.getInteger(Entity.java:213)
        at com.splunk.Job.getEventCount(Job.java:252)

Change the code to toLong() should be enough of a fix.

**Comment by shakeelmohamed** [comment]
Thanks for the bug report @francispage.

We're open to a pull request against the `develop` branch if you're interested in doing the work

**Comment by shakeelmohamed** [comment]
We've added a fix on the develop branch, 842702e625fdf6fad7eb7d902f5ec02a9ca353e2 which will be out in the next release.
