### ISSUE TITLE
savedSearch.dispatch throws NullPointerException 

### ISSUE THREAD

**Issue by joe96814** [splunk/splunk-sdk-java#83]
I am getting an NPE when calling the dispatch method on a savedSearch.  Tracing the code the NPE is occurring in ResourceCollection.java in the namespace(AtomEntry entry) method.  The issue is entityMetadata is set using entry.content.get("eai:acl"), but this returns null and entityMetadata is never checked for null.  Surrounding this call with a null check resolves the issue and gives the expected number of events back.  

Also note this issue actually appears to be a timing related issue because if I debug starting at the dispatch method and step through the code until I reach the call to validate and step over validate everything runs fine, no null pointer and I get the expected results back.

The stack trace is below:

`Exception in thread "main" java.lang.NullPointerException 
at com.splunk.ResourceCollection.namespace(ResourceCollection.java:262) 
at com.splunk.ResourceCollection.createItem(ResourceCollection.java:161) 
at com.splunk.ResourceCollection.load(ResourceCollection.java:295) 
at com.splunk.ResourceCollection.refresh(ResourceCollection.java:334) 
at com.splunk.ResourceCollection.refresh(ResourceCollection.java:29) 
at com.splunk.Resource.validate(Resource.java:174) 
at com.splunk.ResourceCollection.validate(ResourceCollection.java:350) 
at com.splunk.ResourceCollection.get(ResourceCollection.java:184) 
at com.splunk.SavedSearch.dispatch(SavedSearch.java:87) 
at com.splunk.SavedSearch.dispatch(SavedSearch.java:106) 
at com.splunk.SavedSearch.dispatch(SavedSearch.java:63)`

**Comment by itay** [comment]
@joe96814 A few questions:

1. Which version of Splunk are you using? 
2. Do you happen to be using Search Head Clustering?
3. If the answer to (3) is yes, are you talking to a specific SH always, or do you have an LB in front of them that you're talking to?

**Comment by joe96814** [comment]
I am using Splunk Java SDK 1.5, the server itself is host on splunkcloud and is version 6.3.0.4.  I will have to confirm with our admin, but I am guessing there is Search Head Clustering with a LB in front.

**Comment by geonspapa** [comment]
My env is 6.3.3 shc. Same problem occured. Problem is not fixed?

**Comment by df-sandiego** [comment]
Has anyone got any answer yet on this issue?  I got the exact same problem.

**Comment by tim-suchanek** [comment]
6.4.4
yes, LB in front of SH
any other solution suggestion then to switch of LB?

**Comment by shakeelmohamed** [comment]
Hi everyone, 
we have a fix in the develop branch (7a952a56ad6071c94e4e35bafe5a8956bff7ea2f), and we're looking to push out a release soon.

**Comment by aramachandranintuit** [comment]
is this issue fixed ?
