### ISSUE TITLE
Saved search throws a Null pointer exception

### ISSUE THREAD

**Issue by aramachandranintuit** [splunk/splunk-sdk-java#97]
when running a saved search instance through splunk API , i get the following exception

"main" java.lang.NullPointerException
	at com.splunk.ResourceCollection.namespace(ResourceCollection.java:262)
	at com.splunk.ResourceCollection.createItem(ResourceCollection.java:161)
	at com.splunk.ResourceCollection.load(ResourceCollection.java:295)
	at com.splunk.ResourceCollection.refresh(ResourceCollection.java:334)
	at com.splunk.ResourceCollection.refresh(ResourceCollection.java:1)
	at com.splunk.Resource.validate(Resource.java:174)
	at com.splunk.ResourceCollection.validate(ResourceCollection.java:350)
	at com.splunk.ResourceCollection.get(ResourceCollection.java:184)
	at com.splunk.SavedSearch.dispatch(SavedSearch.java:87)
	at com.splunk.SavedSearch.dispatch(SavedSearch.java:106)
	at com.splunk.SavedSearch.dispatch(SavedSearch.java:63)

**Comment by tdhellmann** [comment]
Hi @aramachandranintuit - which version of the Splunk SDK for Java are you using and which version of Java are you using?

**Comment by aramachandranintuit** [comment]
1.5.0 and 1.6.0 are also giving me the same exceptions.

If there is a version of Splunk SDK that has the fix for the above issue , please let me know the version number of the same so that i can add it as a maven dependency.

**Comment by tdhellmann** [comment]
1.6.1 should have a fix for that specific issue - a null reference check was added at line 262 of ResourceCollection.java. Can you try that version and let me know?

**Comment by clayroach** [comment]
@aramachandranintuit - was there a resolution for this?  I am seeing something similar in v1.6.2.0

**Comment by aramachandranintuit** [comment]
I worked around this issue by not using that workflow. I don't think they
solved it.

**Comment by liketic** [comment]
@aramachandranintuit I cannot reproduce this on latest version. Could you please confirm that? And if still happens, please provide more informations. Thanks!

**Comment by clayroach** [comment]
We are seeing this still in v1.6.2.0, with Splunk v6.4.7.  We just ran into this again today.

**Comment by liketic** [comment]
@clayroach Can you try v1.6.3.0?

**Comment by clayroach** [comment]
We can try but didn't look like any commits since 1.6.2 would address this.

**Comment by j9reid** [comment]
This continues to hamper data collection at our customer. Any updates on this?

**Comment by liketic** [comment]
@j9reid Could you please provide the steps to reproduce this issue？

**Comment by shakeelmohamed** [comment]
Closed to due to lack of information. Please re-open if anyone has more details.
